server:
  port: 19090

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:14306/gogo_shop
    username: root
    password: password

  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/auth/callback/{registrationId}"
            client-name: naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

front-end-url: ${FRONTEND_URL:http://localhost:3000}
cors-allowed-origins: http://localhost:3000,${front-end-url}
token-expire-seconds: 3_600
token-key: ${TOKEN_KEY:7B9476CED2F62DBC3A323A4B7E8B312C}
token-cookie-name: ${TOKEN_KEY:token}