version: "2.2"

services:
  mysql8:
    image: mysql:latest
    container_name: mysql8
    ports:
      - "14306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gogo_shop
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql8-gogo-shop:/var/lib/mysql

volumes:
  mysql8-gogo-shop:
    driver: local